# ===========================================================================================
# DXlog FILENAME-creator by DL8RDL (c) 2026 - configuration file
# Comments are allowed, start lines containing your comment with # (semicolon)  or  # (pound)
#
# ------------------->>>  THIS FILE MUST BE ENCODED IN UTF-8  <<<-------------------
#
# ===========================================================================================

[Settings]
Path=C:\DXLOG-Data\DXLOG-ContestLogs\1977\
Callsign=da2n
Year=1977
DXLogPath=C:\Program Files (x86)\DXLog.net\DXLog.net.exe

[Modes]
# your desired modes here
CW
SSB
MIXED
RTTY
FT8
FT4

[Readme]
# you can edit and upgrade your helpfile here
# empty lines will be acceted
# a * at the beginning of your comment-line causes bold fonts
#
# But keep in mind that your ini-changes will be lost if you generate a new ini-file

*Basics

NO INSTALLATION NEEDED!

Just copy two (three) files together in the same directory: 
*dxlog-filename-creator.exe
*dxlog-filename-creator-config.ini
*logo001.png (optional, if you want to have a logo in the upper right)


*Why DXlog-FILENAME-creator and what this program does
In general: DXlog wants you to select a path and a filename for your contest
But, it won´t do it for you. But DXlog FILENAME-creator does!

This program generates directories and files (*.dxn) in your file-system 
for your contests you will work, using DXlog. 

It supports you to get a clean basis for your contest-directories and filenames.
Former WinTest-users will remember: WT did that by default. But DXlog doesn´t.
Therefore I wrote this tiny program for me an all of you.


*How to use
RUN THE PROGRAM
If the config file "dxlog-filename-creator-config.ini" is missing
I ask you to generate a new one.

Make sure that "dxlog-filename-creator-config.ini"
is and remains encoded in
*UTF-8


ENTER THE PATH TO YOUR CONTEST-FILES
Below the given path this program generates a new directory
named with a year-figure, e.g. 2026. See entry-field "year".

You can edit this path completely manually 
*OR
you can browse by clicking the three-dot-button
at the end of the path-entry-line


ENTER YOUR CALLSIGN
Forbidden characters in filesystems are changed to an underscore.


ENTER THE DESIRED YEAR (of e.g. "your" contest-season)
of your contest-season in the field "year"


SELECT YOUR DESIRED CONTEST
you´d like to work. Use the select-field to the left


SELECT THE MODE
of your contest-participation


CLICK THE BIG CREATE-BUTTON
and three things are going to happen:
*	1. the contest-directory will be written
*	2. within this directory an empty (!) *.dxn will be created
*	3. the path where you find the dxn-file of your contest will be copied to clipboard
*   4. if neccessary, the program-window stays open in case you´d like to prepare more contests.
*   5. the path copied to clipboard always is the last generated one


*Run DXlog
You will be asked wether you´d like to run DXlog now or not. Your choice.
DXlog will be launched in that given path you can see in the bottom-line.
Usually this is c:\Program Files (x86)\DXLog.net\DXLog.net.exe

If you´re in need to change this path according to the installation on 
your machine you can do so! You can edit this path completely manually 
*OR
you can browse by clicking the three-dot-button
at the end of the path-entry-line.
finally you alwas have to select the file "DXLog.net.exe"

In case when you change the path:
always make sure to have "DXLog.net.exe" written at the end of this path.
Otherwise DXlog will not launch.


*Generate new contest
In DXlog you might want to open a brandnew contest.
There you configure your new contest.


*Save and start the new contest
Here the real power of this program takes place.
DXlog wants you to select a path and a filename for your contest
But, it won´t do it for you. But DXlog FILENAME-creator does!

Since you have the copied path in your clipboard you just have to paste the stored path to your fileselect-box and BOOOM, you´re there!


*The contest-file
The contest-file is already there! But keep in mind: In this second it still is empty. 

You just select the empty file (if you´re as lazy as I am! :-) and save your contest in that file.


*Now your done. 


If you like this program: use and distribute it as often as you want for free - ham-spirit-policy ;-) If you want to contact me you can do this by mail:
*dl8rdl@darc.de




[Contests]
# all your needed contests. You can edit here or change however you like.
# this list contains supported contests supported by DXlog.
# current list: updated in 2026-08
10-10 QSO Party
13 Colonies Special Event
7th Call Area QSO Party (7QP)
9A Activity
9A CW
9A DX
9KCC 15-m Contest
A.R.I. International DX Contest
A1CLUB Weekly Contest
AGB Party Contest
AGCW Handtastenparty
AGCW Happy New Year Contest
AGCW QRP Contest
AGCW QRP-QRP-Party
AGCW VHF/UHF-Contest
AGCW YL-CW Party
AGCW–NTC Friendship QSO Party
AM-Testen
ARAM 50MHz Contest
ARI 40/80
ARI Sezioni
ARRL 10-Meter Contest
ARRL 160-Meter Contest
ARRL DX
ARRL Field Day
ARRL International EME Contest
ARRL January VHF Contest
ARRL June VHF Contest
ARRL RTTY Roundup
ARRL Rookie Roundup
ARRL School Club Roundup
ARRL September VHF Contest
ARRL Sweepstakes CW
ARRL Sweepstakes SSB
ASIA-PACIFIC Sprint Contest
Aegean RTTY Contest
Africa All Mode International DX Contest
Alabama QSO Party (AQP)
All Asian
All Austrian 160m Contest
All JA Contest
Antique Wireless Association CW Activity Day
Araucária VHF Contest
Argentina National 40m Contest
Arizona QSO Party (AZQP)
Arkansas QSO Party (ARQP)
Arktika Cup
Arktika Cup Digital
Asiatic Russia Championship
Atlantic Canada QSO Party (ACQP)
BALKAN HF CONTEST
BARTG HF RTTY Contest
BARTG PSK63 SPRINT Contest
BARTG RTTY SPRINT Contest
BARTG RTTY SPRINT75 Contest
BCC QSO Party
BDM RTTY WW Contest
Baltic Contest
Baltic Open VUSHF Contest
Black Sea Cup International (BSCC)
Border Guard Day (RCPW)
British Columbia QSO Party (BCQP)
Bucuresti HF Contest
CBJ-DX Contest
CCF Joulusprint
CIS DX PSK Contest
CN de Sufijos
CNCW
CQ Bande Basse Italia
CQ Vojvodina
CQ WPX
CQ WPX RTTY Contest
CQ WW 160-Meter Contest
CQ World Wide
CQ World Wide RTTY
CQ World Wide VHF Digital
CQ World Wide VHF SSB/CW
CQ-M International DX Contest
CQ-WE (Western Electric) Contest
CQMM DX (CQ Manchester Mineira DX) Contest
CVA DX Contest
CWOps - CW Open
CWOps - CWT
California QSO Party (CQP)
Canadian Prairies QSO Party (CPQP)
Casual HF operation
Casual VHF operation
Casual VHF operation (Grid)
Chile WPX Contest - CE station
Chile WPX Contest - DX station
Cimrman´s Clandestine Contest (CUC)
Colorado QSO Party (COQP)
Concurso CW/Brasil
Concurso Marechal Rondon
Concurso Municipios Espanoles
Concurso Nacional Fonia
Croatian Activity Contest
Czech Activity Contest VHF/UHF/SHF
DARC 10m Contest
DARC 10m DIGITAL Contest (Corona)
DARC Ausbildungscontest
DARC Easter Contest
DARC HSW Contest
DARC RTTY Short Contest
DARC V/U/SHF Wettbewerb
DARC XMAS-Contest
DARC YL Contest
DDFM 50MHz
DIG QSO PARTY
DIG-R Activity day
DL-DX-RTTY
DMC RTTY Contest
DRCG World Wide RTTY
DTC - German Telegraphy Contest
DXPedition mode
DXPedition with QO-100
Day of Radio
Delaware QSO Party (DEQP)
Dzień Dziecka
E7 6m Cup
E7 Activity contest
EA PSK63 Contest
EA RTTY Contest
EPC PSK63 QSO Party
EPC Russia DX Contest
EPC Ukraine DX Contest
EPC WW DX Contest
ES Kasivoti
ES Open Championship
ES-LL-KV
ES-LL-Valipaev
ES-ULL-KV
EU HF Championship
EU PSK DX Contest
EU Sprint
EU V/U/SHF
EU V/U/SHF with gridsquare multiplier
EUCW 160m CW party
EURASIA HF Championship
European Union DX Contest
FIRAC HF Contest
FISTS Sprint
FOC BW QSO PARTY
FOC Marathon
Farroupilha Contest
Farroupilha Contest VHF
Florida QSO Party (FQP)
Four QSO Party (IN7QPNEDE)
Georgia QSO Party (GQP)
HA3NS Sprint Memorial Contest
HA_HF_IFI
HA_VHF_IFI
HF KUP SRRS
HF+VHF/UHF DXPedition mode
HRVATSKI RADIOAMATERSKI KUP
HSC Contest
Ham Spirit Contest
HamCation QSO Party
Hawaii QSO Party (HIQP)
Hawaii QSO Party (HIQP) HI station
Helvetia Contest
Hessen Contest KW
Hessen Contest UKW
His Majesty The King of Spain
Holyland Contest
Hungarian DX Contest
IAC VHF
IAFA Day Contest
IARU HF Championship
IARU R1 2M CONTEST
IARU R1 50MHz F8SH Memorial
IARU R1 6M CONTEST
IARU R1 70CM & UP CONTEST
IARU Region 1 Fieldday (DARC)
ICWC Medium Speed Test
IG-RY World Wide RTTY Contest
INDEXA Worldwide QSO Party
INORC Contest
IPARC Contest
IRON HAM Contest
IRTS 2M&70CMS Counties Contest
IRTS HF Counties Contest
Idaho QSO Party (IDQP)
Illinois QSO Party (ILQP)
Indiana QSO Party (INQP)
International Naval Contest
Iowa QSO Party (IAQP)
Istra Open Contest
JARL WW RTTY Contest
JARTS WW RTTY CONTEST
JOTA-JOTI
Japan International DX Contest
K.S. Sainion muistokilpailu
K1USN Slow Speed Open
K1USN Slow Speed Test
KCJ Contest
KCJ Topband Contest
KT KUP Srbije
KT SCWC
KUP JADRANA
KV PRVENSTVO ZRS
Kalakukko
Kansas QSO Party (KSQP)
Kentucky QSO Party (KYQP)
Kesäkisa
Kirov Region Cup
LABRE DX Contest
LABRE QRS-10 Contest
LY VHF/UHF/SHF Contest
LZ DX
LZ DX VHF/UHF Contest
LZ HF Championship
LZ HF FIELD 40m
LZ HF Field Day "Karlovo"
LZ MILARA
LZ VHF Field Day
LZ Vasil Levski
Latvijas Republikas proklamēšanas īsviļņu sacensības
Latvijas īsviļņu sacensības 80m
Lithuanian Ultrashort Wave Championship
Louisiana QSO Party (LAQP)
Lubelski Lipiec 1980
Lynx Dx Group Vertical 4 Estaciones
MRAI - DL6RAI Memorial Contest
Maidenhead Mayhem
Maine QSO Party (MEQP)
Makrothen Contest
Maratona QRS 10
Marconi Club ARI Loano QSO Party Day
Marconi Club ARI Loano Slow CW QSO Party
Marconi Memorial HF
Marconi Memorial VHF
Maryland-DC QSO Party (MDQP)
Masonic Lodges on the Air
Michigan QSO Party (MIQP)
Minnesota QSO Party (MNQP)
Mississippi QSO Party (MSQP)
Mississippi QSO Party (MSQP) MS Station
Missouri QSO Party (MOQP)
Montana QSO Party (MTQP)
Moscow Cup CW
Moscow HF Championship
NAC MGM
NAC Open
NAC V/U/SHF
NAC Weekend V/U/SHF
NAQP - North American QSO Party
NAQP RTTY - North American QSO Party, RTTY
NCCC Sprint (NS)
NRAU - Baltic Contest
NRAU NAC 10m Contest
NRRL Field Day HF
NRRL Field Day VHF
NRRL Fylkestest
NRRL MGM Weekend
NRRL Manedstest
NRRL Telefonitest
NRRL Vintertest
NTC Anniversary Party
NTC QSO Party
Naranja CW
Nauryz DX Contest
Nebraska QSO Party (NEQP)
Nevada QSO Party HF (NVQP)
New England QSO Party (NEQP)
New Hampshire QSO Party (NHQP)
New Jersey QSO Party (NJQP)
New Mexico QSO Party (NMQP)
New York QSO Party (NYQP)
North American SSB Sprint
North American Sprint
North Carolina QSO Party (NCQP)
North Dakota QSO Party (NDQP)
Not- und Kat-Funk Übung
Novi Beograd
OK DX RTTY Contest
OK-OM DX Contest
OK1WC Memorial HF Contest
ORARI DX Contest (YB station)
ORARI DX Contest - DX station
Oceania DX
Ogólnopolskich Zawodów QRP "Memorial SP9DT"
Ohio QSO Party (OHQP)
Oklahoma QSO Party (OKQP)
Old New Year Contest
Ontario QSO Party (OQP)
Open Ukraine RTTY Championship
Original QRP Contest
PA Beker
PACC Contest
PACCdigi Contest
PGA Test
PGA-DIGI
PODXS 160 Meter Great Pumpkin Sprint
PODXS 31 Flavors Contest
PODXS 40 Meter Firecracker Sprint
PODXS 80 Meter Jay Hudak Memorial Sprint
PODXS PSKFest
PODXS Saint Patrick's Day Contest
PODXS Three Day Weekend Contest
PODXS Triple Play Low Band Sprint
PODXS Valentine Sprint
POPOV Memorial Contest
POTA activation
PRO CW Contest
PRO Digi Contest
Pennsylvania QSO Party (PAQP)
Poisson d'Avril
Polar Radioman Contest
Polska WW BPSK63 Contest
Portugal Day Contest
Puskás Kupa URH
QRP HF RTTY Contest
Quebec QSO Party (QCQP)
RAC Canada Day Contest
RAC Canada Winter Contest
RAEM International Contest
RCC Fieldday
RCC-CUP
RCWC Mini-test
RCWC RPX Contest
RDA Contest
REF 160m Contest
REF THF Contest
REF contest
RH-OB_CW
RH-OB_MIX
RH-OB_SSB
RSGB 1.8MHz AFS (Club Calls) Contest
RSGB 1.8MHz Contest
RSGB 144/432MHz Low Power Contest
RSGB 144MHz May Contest
RSGB 50MHz Trophy
RSGB 6m/4m AFS Contests
RSGB 70MHz Trophy
RSGB 80m Club Championship
RSGB 80m Club Championship Data
RSGB Affiliated Societies Contests
RSGB Affiliated Societies Data Contest
RSGB CW Field Day
RSGB Commonwealth Contest
RSGB International DX Contest
RSGB International Low Power Contest
RSGB RoLo Contest
RSGB SSB Field Day
RSGB UKAC VHF/UHF/SHF
RSGB VHF Christmas Cumulatives
RSGB VHF M1
RSGB VHF M4
RSGB VHF NFD
RT3A Sprint Memorial Contest
RTC Contest
RTC Test Contest
RTTY Cup "MSK TIME"
RTTYops WW DX Contest
RTTYops Weekend Sprint
RTTYops Weeksprint
Rencontres UFT
Rheinland-Pfalz Aktivitätsabend 2m
Rheinland-Pfalz Aktivitätsabend 70cm
Rheinland-Pfalz Aktivitätsabend 80/10m
Riachuelo Contest
Russian 160m contest
Russian DX contest
Russian Radio Team Championship
Russian WW Digital Contest
Russian WW MultiMode Contest
Russian WW PSK Contest
Russian YL/OM Contest
Russian «RADIO» RTTY WW Contest
SA Sprint
SAMOVAR
SARL 80m QSO Party
SARL HF Contest
SARL YL QSO Party
SARL Youth QSO Party
SARTG New Year RTTY Contest
SARTG WW RTTY Contest
SCC RTTY Contest
SL-Testen
SP DX Contest
SPDX RTTY Contest
SPRINT VGE
SRR Digital Cup
SSA 100 Year Anniversary
SSA JULTEST
SSA Portabeltest
SSA-MT-CW
SSA-MT-SSB
Sainio CW Contest
Sainio RTTY Contest
Sainio SSB Contest
Samuel Morse Memorial Contest
Saratov Region Cup
Scandinavian Activity Contest (SAC)
Schwaben Contest KW
Schwaben Contest UKW
Scottish DX Contest
Silent Key Memorial Contest
Solar Eclipse QSO Party
South America 10m Contest
South America Integration Contest CW (SACW)
South Carolina QSO Party (SCQP)
South Dakota QSO Party (SDQP)
Spring Polar Sprint
Stew Perry Top Band Distance Challenge
Swiss Activity Contest
TA VHF UHF Contest
TA World-Wide DX Contest
TA World-Wide DX Contest RTTY
TARA RTTY Melee Contest
TESLA Memorial HF CW Contest
TRC DIGI Contest
TRC-DX Contest
Telephone Pioneers QSO Party (TPQSO)
Ten-Meter RTTY Contest
Tennessee QSO Party (TNQP)
Tesla Memorijal V/U/SHF Contest
Texas QSO Party (TXQP)
Tisza Cup
Trans-Tasman Low-Band Contest
Triathlon DX contest
Tuesday's Telegraphy Contest by SPCWC
U-QRQ-C Contest
UA1DZ Memorial Cup
UA1DZ Memorial Cup (SP/LO)
UA2 QSO Party
UBA Contest
UBA ON Contest 2m
UBA ON Contest 6m
UBA ON Contest HF
UBA PSK63 Prefix Contest
UBA Spring Contest 2m
UBA Spring Contest 6m
UBA Spring Contest HF
UCC Contest
UK BOTA activation
UK DX BPSK63 Contest
UKEICC 80m Summer Series
UKEICC80
UKEIDX Contest
UKSMG Summer Contest
UN DX Contest
URC DX RTTY Contest
URH_OB_CW
URH_OB_MIX
URH_OB_SSB
USKA Christmas Contest
USKA Field Day
Ukrainian DX Classic RTTY Contest
Ukrainian DX Contest (URDXC)
Ukrainian DX DIGI Contest
Ukrainian Radio Sport Team Championship
Ural Cup HF
VHF KUP SRRS
VK Shires Contest
VOLTA RTTY DX Contest
VU International DX Contest
Vermont QSO Party (VTQP)
Veteran
Vidovdan
Viitosten syysottelu
Virginia QSO Party (VAQP)
WAEDC RTTY
WAPC - Worked All Provinces of China DX Contest
WIA Remembrance Day Contest
WRTC 2014
WRTC 2018
WRTC 2022
WRTC 2026
WW PMC Contest
WWFF Green Party
WWFF activation
WWSA CW
Washington State QSO Party (Salmon Run)
Wednesday mini-contest
Weekly Phone Test (Phone Fray)
Weekly RTTY Test
West Virginia QSO Party (WVQP)
Winter Field Day
Wisconsin QSO Party (WIQP)
Worked All Europe DX
Worked All Germany
World Time Zone Challenge
World Wide Argentina DX Contest
World Wide Award Event (WWA)
World Wide Digi DX Contest
Worldwide Sideband Activity Contest
XE RTTY International Contest
YB DX Contest RTTY
YB DX Contest SSB
YBDXPI SSB Contest
YL OM Verseny
YLRL DX/NA-YL Anniversary Contest
YLRL YL OM Contest
YO DX
YO International PSK31 Contest
YOTA Contest
YU DX
YU KT Maraton
YU UKT Aktiviti
Yuri Gagarin International DX Contest
Yuri Gagarin International DX Contest Satellite
ZIMSKI KV KUP
ZS1 QSO Party
ZS2 QSO Party
ZS3 QSO Party
ZS4 QSO Party
ZS5 QSO Party
Zagreb FM Contest
Zawody Rybnickie
Zawody SPOTC
Šumadija kup
Šumadija kup PSK
Две Столицы
Идёт охота на Волков
Кубок России на КВ телеграфом
Кубок России auf КВ телефон
Открытый Championat Udmurtii
Чемпионат РФ CW
Чемпионат РФ SSB